/**
 * This file is generated by openapi-typescript.
 * Run: npm run generate:api
 */
export interface components {
  schemas: {
    LoginRequest: { username: string; password: string };
    LoginResponse: { accessToken: string };
    SpotRequest: {
      code: string;
      name: string;
      description: string;
      tags?: string[] | null;
      lat?: number | null;
      lng?: number | null;
      isPublished?: boolean;
    };
    SpotResponse: {
      id: string;
      code: string;
      name: string;
      description: string;
      tags?: string[] | null;
      lat?: number | null;
      lng?: number | null;
      isPublished: boolean;
      updatedAt: string;
    };
    PublishRequest: { isPublished: boolean };
    EventRequest: {
      title: string;
      description?: string | null;
      startsAt: string;
      endsAt: string;
      lat?: number | null;
      lng?: number | null;
      locationText?: string | null;
      isPublished?: boolean;
    };
    EventResponse: {
      id: string;
      title: string;
      description?: string | null;
      startsAt: string;
      endsAt: string;
      lat?: number | null;
      lng?: number | null;
      locationText?: string | null;
      isPublished: boolean;
    };
    OcDayRequest: { date: string; name?: string | null };
    OcDayResponse: { id: string; date: string; name?: string | null };
    VisitLogResponse: {
      id: string;
      sessionId: string;
      eventType: string;
      spotCode?: string | null;
      occurredAt: string;
      createdAt: string;
    };
  };
}

export interface paths {
  '/admin/auth/login': {
    post: {
      requestBody: {
        content: { 'application/json': components['schemas']['LoginRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['LoginResponse'] };
        };
      };
    };
  };
  '/admin/spots': {
    get: {
      responses: {
        200: {
          content: { 'application/json': components['schemas']['SpotResponse'][] };
        };
      };
    };
    post: {
      requestBody: {
        content: { 'application/json': components['schemas']['SpotRequest'] };
      };
      responses: {
        201: {
          content: { 'application/json': components['schemas']['SpotResponse'] };
        };
      };
    };
  };
  '/admin/spots/{id}': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['SpotResponse'] };
        };
      };
    };
    put: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['SpotRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['SpotResponse'] };
        };
      };
    };
    delete: {
      parameters: { path: { id: string } };
      responses: {
        204: never;
      };
    };
  };
  '/admin/spots/{id}/publish': {
    patch: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['PublishRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['SpotResponse'] };
        };
      };
    };
  };
  '/admin/spots/{id}/qr': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: {
          content: { 'image/png': Blob };
        };
      };
    };
  };
  '/admin/events': {
    get: {
      responses: {
        200: {
          content: { 'application/json': components['schemas']['EventResponse'][] };
        };
      };
    };
    post: {
      requestBody: {
        content: { 'application/json': components['schemas']['EventRequest'] };
      };
      responses: {
        201: {
          content: { 'application/json': components['schemas']['EventResponse'] };
        };
      };
    };
  };
  '/admin/events/{id}': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['EventResponse'] };
        };
      };
    };
    put: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['EventRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['EventResponse'] };
        };
      };
    };
    delete: {
      parameters: { path: { id: string } };
      responses: {
        204: never;
      };
    };
  };
  '/admin/events/{id}/publish': {
    patch: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['PublishRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['EventResponse'] };
        };
      };
    };
  };
  '/admin/oc-days': {
    get: {
      responses: {
        200: {
          content: { 'application/json': components['schemas']['OcDayResponse'][] };
        };
      };
    };
    post: {
      requestBody: {
        content: { 'application/json': components['schemas']['OcDayRequest'] };
      };
      responses: {
        201: {
          content: { 'application/json': components['schemas']['OcDayResponse'] };
        };
      };
    };
  };
  '/admin/oc-days/{id}': {
    delete: {
      parameters: { path: { id: string } };
      responses: {
        204: never;
      };
    };
  };
  '/admin/logs/recent': {
    get: {
      parameters: { query?: { limit?: number } };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['VisitLogResponse'][] };
        };
      };
    };
  };
}
