/**
 * This file is generated by openapi-typescript.
 * Run: npm run generate:api
 */
export interface components {
  schemas: {
    LoginRequest: { username: string; password: string };
    LoginResponse: { accessToken: string };
    SpotRequest: {
      code: string;
      name: string;
      description: string;
      tags?: string[] | null;
      lat?: number | null;
      lng?: number | null;
      isPublished?: boolean;
    };
    SpotResponse: {
      id: string;
      code: string;
      name: string;
      description: string;
      tags?: string[] | null;
      lat?: number | null;
      lng?: number | null;
      isPublished: boolean;
      updatedAt: string;
    };
    PublishRequest: { isPublished: boolean };
    EventRequest: {
      title: string;
      description?: string | null;
      startsAt: string;
      endsAt: string;
      lat?: number | null;
      lng?: number | null;
      locationText?: string | null;
      isPublished?: boolean;
    };
    EventResponse: {
      id: string;
      title: string;
      description?: string | null;
      startsAt: string;
      endsAt: string;
      lat?: number | null;
      lng?: number | null;
      locationText?: string | null;
      isPublished: boolean;
    };
    OcDayRequest: { date: string; name?: string | null };
    OcDayResponse: { id: string; date: string; name?: string | null };
    OpenCampusTimeslotResponse: {
      id: string;
      eventId: string;
      startsAt: string;
      endsAt: string;
    };
    QrIssueRequest: { expiresAt?: string | null };
    TimeslotSummary: { timeslotId: string; startsAt: string; endsAt: string };
    QrIssueResponse: {
      qrIssueId: string;
      eventId: string;
      timeslotId: string;
      issuedAt: string;
      expiresAt: string;
      revokedAt?: string | null;
      revokeReason?: string | null;
      scanCount: number;
      lastScannedAt?: string | null;
      url: string;
      timeslot?: components['schemas']['TimeslotSummary'];
    };
    RevokeQrIssueRequest: { reason?: string | null };
    VisitLogResponse: {
      id: string;
      sessionId: string;
      eventType: string;
      spotCode?: string | null;
      occurredAt: string;
      createdAt: string;
    };
  };
}

export interface paths {
  '/admin/auth/login': {
    post: {
      requestBody: {
        content: { 'application/json': components['schemas']['LoginRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['LoginResponse'] };
        };
      };
    };
  };
  '/admin/spots': {
    get: {
      responses: {
        200: {
          content: { 'application/json': components['schemas']['SpotResponse'][] };
        };
      };
    };
    post: {
      requestBody: {
        content: { 'application/json': components['schemas']['SpotRequest'] };
      };
      responses: {
        201: {
          content: { 'application/json': components['schemas']['SpotResponse'] };
        };
      };
    };
  };
  '/admin/spots/{id}': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['SpotResponse'] };
        };
      };
    };
    put: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['SpotRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['SpotResponse'] };
        };
      };
    };
    delete: {
      parameters: { path: { id: string } };
      responses: {
        204: never;
      };
    };
  };
  '/admin/spots/{id}/publish': {
    patch: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['PublishRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['SpotResponse'] };
        };
      };
    };
  };
  '/admin/spots/{id}/qr': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: {
          content: { 'image/png': Blob };
        };
      };
    };
  };
  '/admin/events': {
    get: {
      responses: {
        200: {
          content: { 'application/json': components['schemas']['EventResponse'][] };
        };
      };
    };
    post: {
      requestBody: {
        content: { 'application/json': components['schemas']['EventRequest'] };
      };
      responses: {
        201: {
          content: { 'application/json': components['schemas']['EventResponse'] };
        };
      };
    };
  };
  '/admin/events/{id}': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['EventResponse'] };
        };
      };
    };
    put: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['EventRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['EventResponse'] };
        };
      };
    };
    delete: {
      parameters: { path: { id: string } };
      responses: {
        204: never;
      };
    };
  };
  '/admin/events/{id}/timeslots': {
    get: {
      parameters: { path: { id: string } };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['OpenCampusTimeslotResponse'][] };
        };
      };
    };
  };
  '/admin/events/{id}/publish': {
    patch: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['PublishRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['EventResponse'] };
        };
      };
    };
  };
  '/admin/qr-issues': {
    get: {
      parameters?: { query?: { eventId?: string } };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['QrIssueResponse'][] };
        };
      };
    };
  };
  '/admin/timeslots/{timeslotId}/qr-issues': {
    post: {
      parameters: { path: { timeslotId: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['QrIssueRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['QrIssueResponse'] };
        };
      };
    };
  };
  '/admin/qr-issues/{id}/revoke': {
    post: {
      parameters: { path: { id: string } };
      requestBody: {
        content: { 'application/json': components['schemas']['RevokeQrIssueRequest'] };
      };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['QrIssueResponse'] };
        };
      };
    };
  };
  '/admin/oc-days': {
    get: {
      responses: {
        200: {
          content: { 'application/json': components['schemas']['OcDayResponse'][] };
        };
      };
    };
    post: {
      requestBody: {
        content: { 'application/json': components['schemas']['OcDayRequest'] };
      };
      responses: {
        201: {
          content: { 'application/json': components['schemas']['OcDayResponse'] };
        };
      };
    };
  };
  '/admin/oc-days/{id}': {
    delete: {
      parameters: { path: { id: string } };
      responses: {
        204: never;
      };
    };
  };
  '/admin/logs/recent': {
    get: {
      parameters: { query?: { limit?: number } };
      responses: {
        200: {
          content: { 'application/json': components['schemas']['VisitLogResponse'][] };
        };
      };
    };
  };
}
