import type { FloorMap } from '@nexus/shared';
import type { MapSpot } from '../../types/navigation';

export const fallbackSpots: MapSpot[] = [
  {
    id: 'reception',
    name: '受付',
    floor: '1F',
    x: 28,
    y: 58,
    congestion: 'normal',
    category: '受付・案内',
    tags: ['パンフレット受け取り', '困ったときの相談先', 'スタッフ常駐'],
    kind: 'support',
    relatedEventId: 'reception',
    relatedEvents: 2,
    travelEstimate: '現在地から約1分',
  },
  {
    id: 'lecture-room',
    name: '講義室',
    floor: '1F',
    x: 54,
    y: 34,
    congestion: 'normal',
    category: '説明会会場',
    tags: ['学校説明', '工学部説明会'],
    kind: 'place',
    relatedEventId: 'engineering-briefing',
    relatedEvents: 2,
    travelEstimate: '受付から約2分',
  },
  {
    id: 'practice-area',
    name: '実習エリア',
    floor: '1F',
    x: 70,
    y: 63,
    congestion: 'busy',
    category: '実習施設',
    tags: ['体験授業', '航空・ものづくりの学び'],
    kind: 'place',
    relatedEventId: 'experience-class',
    relatedEvents: 1,
    travelEstimate: '受付から約4分',
  },
  {
    id: 'consultation-room',
    name: '相談会場',
    floor: '1F',
    x: 43,
    y: 73,
    congestion: 'empty',
    category: '相談',
    tags: ['保護者向け相談', '学費・寮・進路'],
    kind: 'support',
    relatedEventId: 'parent-consultation',
    relatedEvents: 2,
    travelEstimate: '受付から約2分',
  },
  {
    id: 'restroom',
    name: 'トイレ',
    floor: '1F',
    x: 82,
    y: 42,
    congestion: 'normal',
    category: '設備',
    tags: ['詳しい場所は受付で確認できます'],
    kind: 'place',
    relatedEvents: 0,
    travelEstimate: '現在地から約2分',
  },
  {
    id: 'entrance',
    name: '出入口',
    floor: '1F',
    x: 16,
    y: 72,
    congestion: 'normal',
    category: '出入口',
    tags: ['集合・解散の目印'],
    kind: 'support',
    relatedEvents: 0,
    travelEstimate: '受付から約1分',
  },
  {
    id: 'current-location',
    name: '現在地（仮）',
    floor: '1F',
    x: 31,
    y: 52,
    congestion: 'normal',
    category: '現在地',
    tags: ['仮表示です', '詳しい位置は受付・スタッフへ'],
    kind: 'current',
    relatedEvents: 0,
    travelEstimate: '現在地として仮表示中',
  },
];

export const fallbackFloors: FloorMap[] = [
  { id: '1f', name: '1F', width: 320, height: 220 },
  { id: 'outdoor', name: '屋外', width: 320, height: 220 },
];
